language: python

python:
    - 3.6

install:
    - pip install --upgrade -r dmms/requirements.txt

services:
    - mysql

before_script:
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS company_db;'
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS test_company_db;'
  - mysql -u root -e "CREATE USER 'manager_user'@'%' IDENTIFIED BY 'hard_password1234';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'manager_user'@'%';"


env:
  - ENV='TEST'

script:
    - python dmms/tests/test_rest/test_rest.py
