language: python

python:
    - 3.6

install:
    pip install --upgrade -r department_managment_mini_system/requirements.txt

services:
    mysql

before_script:
  - mysql -e 'CREATE USER 'manager_user'@'%' IDENTIFIED BY 'hard_password1234';'
  - mysql -e 'GRANT ALL PRIVILEGES ON *.* TO 'manager_user'@'%';'
  - mysql -e 'CREATE DATABASE company_db;'
  - mysql -e 'CREATE DATABASE test_company_dbb;'

jobs:
    include:
        - language: python
          python: 3.6
          env:
              - ENV='TEST'
          script:
              - python department_managment_mini_system/tests/test_rest/test_rest.py

script:
    pylint *
    gunicorn --bind localhost:5000 department_managment_mini_system/wsgi:app_rest
    gunicorn --bind localhost:5001 department_managment_mini_system/wsgi:app_views
